parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '8889'
    database_name: ergometrix
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: root
    mailer_password: root
    locale: fr
    secret: 85ec8ed10dc3cbcc5bb57d69ec8f3c1051
    database_path: null
