# app/config/security.yml

security:
    encoders:
        Xaj\ErgoBundle\Entity\User: plaintext
            # algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        users:
            entity: { class: XajErgoBundle:User, property: login }

    firewalls:
        main:
            pattern:    ^/
            stateless:  true
            anonymous:  true
            lexik_jwt:
                create_entry_point: true
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer

    # access_control:
    #     - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/admin,       roles: IS_AUTHENTICATED_FULLY }
    #     - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }