# app/config/security.yml

security:
    encoders:
        Xaj\ErgoBundle\Entity\User: 
            algorithm: pbkdf2
            hash_algorithm: sha512
            encode_as_base64: true
            iterations: 1000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        users:
            entity: { class: XajErgoBundle:User, property: login }

    firewalls:
        main:
            pattern:    ^/
            stateless:  true
            anonymous:  true
            lexik_jwt:
                create_entry_point: true
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer

    # access_control:
    #     - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/admin,       roles: IS_AUTHENTICATED_FULLY }
    #     - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }