<?php

namespace Xaj\ErgoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoatRepository extends EntityRepository
{
    /**
     * 
     */
    public function getBoatsNotDeleted()
    {
        $qb = $this->createQueryBuilder('b')
                ->select('b')
                ->where('b.deleted = 0')
                ->orderBy('b.category', 'ASC');

        return $qb->getQuery()->getResult();
    }

    /**
     * 
     */
    public function countTotal()
    {
        return $this->createQueryBuilder('b')
                    ->select('a')
                    ->getQuery()
                    ->getSingleScalarResult();
    }

    /**
     * 
     */
    public function countValid()
    {
        return $this->createQueryBuilder('b')
                    ->select('a')
                    ->where('a.valid = true')
                    ->getQuery()
                    ->getSingleScalarResult();
    }

    /**
     * 
     */
    public function countPayed()
    {
        return $this->createQueryBuilder('b')
                    ->select('a')
                    ->where('a.payment = true')
                    ->getQuery()
                    ->getSingleScalarResult();
    }

    /**
     * 
     */
    public function countByCategory($category)
    {
        return $this->createQueryBuilder('b')
                    ->select('a')
                    ->where('a.category = :cat')
                    ->setParameter('cat', $category)
                    ->getQuery()
                    ->getSingleScalarResult();
    }
}
