<?php

namespace Xaj\ErgoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeaderRepository extends EntityRepository
{
}
